# Generated by Django 6.0 on 2026-01-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='id_proof',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
