# Generated by Django 6.0 on 2026-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_registration_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
