# Generated by Django 6.0 on 2026-03-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='agreement_doc',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
