# Generated by Django 6.0 on 2026-03-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_purchase_agreement_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='razorpay_payment_id',
            field=models.CharField(default=None, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
