# Generated by Django 6.0 on 2026-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_purchase_end_date_purchase_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='end_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
