# Generated by Django 6.0 on 2026-03-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_purchase_end_date_alter_purchase_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.FloatField(),
        ),
    ]
