# Generated by Django 6.0 on 2026-04-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_purchase_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_support',
            name='response',
        ),
        migrations.RemoveField(
            model_name='customer_support',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customer_support',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customer_support',
            name='email',
            field=models.EmailField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customer_support',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer_support',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer_support',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
