# Generated by Django 6.0 on 2026-04-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_customer_support_response_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='agreement_doc',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='property_rights',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='shop_name',
        ),
    ]
