# Generated by Django 5.2.12 on 2026-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
