# Generated by Django 5.2.12 on 2026-04-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_property_property_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_img',
        ),
    ]
